# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('shigongdanwei', models.CharField(default=b'', max_length=128, null=True)),
                ('project_name', models.CharField(default=b'', max_length=128, null=True)),
                ('project_address', models.CharField(default=b'', max_length=2048, null=True)),
                ('project_contact', models.CharField(default=b'', max_length=128, null=True)),
                ('shouhuoren', models.CharField(default=b'', max_length=128, null=True)),
                ('shouhuoren_phone', models.CharField(default=b'', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wxid',
            field=models.CharField(default=b'', max_length=100, verbose_name=b'wechat id'),
        ),
    ]
