# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(default=0)),
                ('label', models.CharField(default='', max_length=128)),
                ('is_new', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=128)),
                ('detail', models.TextField(default='', null=True)),
                ('count', models.IntegerField(default=0)),
                ('min_price', models.IntegerField(default=0)),
                ('max_price', models.IntegerField(default=0)),
                ('is_new', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('sold_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(default=0)),
                ('label', models.CharField(default='', max_length=128)),
                ('value', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Kucun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(default=0)),
                ('guige_list', models.CharField(default='', max_length=128)),
                ('count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
