# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-12 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='goods',
            name='img_list',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='goods',
            name='main_img',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='goods',
            name='short_desc',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
