# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-11 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('goods_id', models.IntegerField(default=0)),
                ('guige_list', models.CharField(default='', max_length=128)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('address_id', models.IntegerField(default=0)),
                ('cart_list', models.TextField(default='')),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
    ]
